/* ChatGPT Macro handoff sidecar for FX TradingDesk. No writes to existing IndexedDB. */
(()=>{'use strict';
const EDGE_KEY='td.edgefinder.snapshots.v1', OUT_KEY='td.chatgpt.macro.reports.v1';
const PAIRS=['EURUSD','GBPUSD','AUDUSD','NZDUSD','USDCAD','USDJPY','CADJPY','EURGBP','EURAUD','EURNZD','EURCAD','EURJPY','AUDCAD','NZDCAD','GBPAUD','GBPNZD','GBPCAD','GBPJPY','AUDNZD','AUDJPY','NZDJPY','USDCHF','EURCHF','GBPCHF','AUDCHF','NZDCHF','CADCHF','CHFJPY'];
const $=s=>document.querySelector(s), safe=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const json=(key)=>{try{return JSON.parse(localStorage.getItem(key)||'[]')}catch{return []}};
const results=()=>{const v=json(OUT_KEY);return Array.isArray(v)?v:[]};
const snapshots=()=>{const v=json(EDGE_KEY);return Array.isArray(v)?v:[]};
const latest=(symbol)=>snapshots().filter(x=>x?.symbol===symbol).sort((a,b)=>String(b.captured_at).localeCompare(String(a.captured_at)))[0]||null;
let selected='EURUSD',notice='';
const time=x=>{if(!x)return 'Unbekannt';const d=new Date(x);return Number.isNaN(d.valueOf())?'Unbekannt':d.toLocaleString('de-CH')};
function readMacros(){return new Promise(resolve=>{let req;try{req=indexedDB.open('fx-trade-desk',1)}catch{return resolve([])}req.onupgradeneeded=()=>{req.transaction.abort()};req.onerror=()=>resolve([]);req.onsuccess=()=>{const db=req.result;if(!db.objectStoreNames.contains('records')){db.close();return resolve([])};try{const tx=db.transaction('records','readonly'),g=tx.objectStore('records').getAll();g.onsuccess=()=>{db.close();resolve((g.result||[]).filter(r=>r?.kind==='macro').sort((a,b)=>String(b.date||'').localeCompare(String(a.date||''))).slice(0,2))};g.onerror=()=>{db.close();resolve([])}}catch{db.close();resolve([])}}})}
function currencyExtract(record,c){const d=record?.currencies?.[c];if(!d||typeof d!=='object')return null;const result={};for(const [k,v] of Object.entries(d)){if(v===null||['string','number','boolean'].includes(typeof v)){if(v!==''&&String(v).length<1500)result[k]=v}}return Object.keys(result).length?result:null}
async function promptPayload(){const snap=latest(selected),macro=await readMacros(),cc=[selected.slice(0,3),selected.slice(3,6)];const macros=macro.map(m=>({date:m.date,title:m.title,reviewed:m.reviewed,global_fields:m.fields||{},currencies:Object.fromEntries(cc.map(c=>[c,currencyExtract(m,c)])),pair_data:m.pairs?.[selected]??null,events:Array.isArray(m.events)?m.events.slice(0,15):[]}));const data={schema_version:'td-macro-handoff-v1',pair:selected,created_at:new Date().toISOString(),edgefinder:snap?{symbol:snap.symbol,captured_at:snap.captured_at,source_updated_at:snap.source_updated_at??null,total_score:snap.total_score,indicators:snap.indicators,warnings:snap.warnings}:null,tradingdesk_macro_records:macros};const preamble=`Du bist mein FX-Makro-Researcher. Analysiere ${selected} für Swing-Trading über 2–10 Handelstage. Nutze die beigefügten EdgeFinder- und TradingDesk-Daten als Ausgangspunkt; überprüfe ihr Alter und behandle fehlende Werte als unbekannt. Recherchiere SELBSTSTÄNDIG im Web aktuelle, relevante Entwicklungen zu beiden Währungen: Zentralbanken und Reden, 3M/12M-Zinserwartungen, 2Y-Renditedifferenzen, Inflation, Arbeit, Wachstum, Risikoappetit, Geopolitik und ggf. Rohstoffe. Wähle eigenständig die wichtigsten Markttreiber aus, nicht nur eine starre News-Liste. Nutze nachvollziehbare Quellen mit Links und Datum. Erfinde keine aktuellen Marktdaten. Unterscheide Fakten, Interpretation und bereits eingepreiste Erwartungen. Keine technische Analyse. Bei unzureichender Evidenz WAIT wählen. Gib zuerst eine knappe Analyse und am Ende einen EINZELNEN gültigen JSON-Codeblock mit EXAKT dieser Struktur (keine Kommentare, keine zusätzlichen Schlüssel): {"schema_version":"td-macro-report-v1","pair":"${selected}","decision":"WAIT","confidence":"low","as_of":"${new Date().toISOString()}","summary":"Begründung","drivers":[{"factor":"Thema","impact":"bullish|bearish|neutral","reason":"Warum relevant","source_url":"https://...","published_at":"YYYY-MM-DD"}],"risks":["Risiko"],"invalidation":["Was ändert den Bias"]}. decision nur LONG, SHORT oder WAIT; confidence nur low, medium, high. Analyse muss die beigefügten Daten kritisch abgleichen.\n\nDATEN:\n`;
return preamble+JSON.stringify(data,null,2)}
function reportValid(x){return !!x&&x.schema_version==='td-macro-report-v1'&&PAIRS.includes(x.pair)&&['LONG','SHORT','WAIT'].includes(x.decision)&&['low','medium','high'].includes(x.confidence)&&typeof x.summary==='string'&&x.summary.length>3&&x.summary.length<25000&&typeof x.as_of==='string'&&!Number.isNaN(Date.parse(x.as_of))&&Array.isArray(x.drivers)&&x.drivers.length<=25&&x.drivers.every(d=>d&&typeof d.factor==='string'&&typeof d.reason==='string'&&['bullish','bearish','neutral'].includes(d.impact)&&(!d.source_url||/^https:\/\//.test(d.source_url)))&&Array.isArray(x.risks)&&Array.isArray(x.invalidation)}
function parseReport(raw){let s=String(raw).trim();const m=s.match(/```(?:json)?\s*([\s\S]*?)```/i);if(m)s=m[1].trim();const obj=JSON.parse(s);if(!reportValid(obj))throw new Error('JSON-Format oder Pflichtfelder ungültig. Bitte den vollständigen ChatGPT-JSON-Codeblock einfügen.');return obj}
function storeReport(x){const all=results();const id=x.pair+'|'+x.as_of;if(!all.some(y=>y.pair+'|'+y.as_of===id)){all.push(x);localStorage.setItem(OUT_KEY,JSON.stringify(all.slice(-150)))}return all}
function render(){const view=$('#view');if(!view)return;const snap=latest(selected),reps=results().filter(x=>x.pair===selected).sort((a,b)=>String(b.as_of).localeCompare(String(a.as_of))),r=reps[0];
view.innerHTML=`<section class="chat-macro"><header><h1>ChatGPT Makroanalyse</h1><p>EdgeFinder + deine TradingDesk-Makrodaten → ChatGPT-Recherche → Analyseimport. Keine API-Schlüssel nötig.</p></header><div class="cm-row"><label for="cm-pair">Währungspaar</label><select id="cm-pair">${PAIRS.map(p=>`<option ${p===selected?'selected':''}>${p}</option>`).join('')}</select><span>EdgeFinder: ${snap?'Score '+safe(snap.total_score)+' · '+safe(time(snap.captured_at)):'Noch keine Daten'}</span></div><div class="cm-actions"><button type="button" class="button button-primary" id="cm-copy">Analyseauftrag kopieren</button><button type="button" class="button button-outline" id="cm-open">ChatGPT öffnen</button></div><p class="cm-hint">1. Auftrag kopieren · 2. ChatGPT öffnen und einfügen · 3. Antwort mit JSON-Codeblock hier importieren. ChatGPT erhält Daten nur, wenn du sie selbst einfügst.</p><label for="cm-response"><strong>ChatGPT-Ergebnis importieren</strong></label><textarea id="cm-response" rows="7" placeholder="JSON-Codeblock aus ChatGPT hier einfügen …"></textarea><div class="cm-actions"><button class="button button-primary" id="cm-import">Analyse speichern</button><button class="button button-outline" id="cm-backup">Analysen exportieren</button></div><p id="cm-status" role="status">${safe(notice)}</p>${r?`<article class="cm-report"><div class="cm-row"><h2>${safe(r.pair)} · ${safe(r.decision)}</h2><strong>Confidence: ${safe(r.confidence)}</strong><span>${safe(time(r.as_of))}</span></div><p>${safe(r.summary)}</p><h3>Markttreiber</h3>${r.drivers.map(d=>`<div class="cm-driver"><strong>${safe(d.factor)} (${safe(d.impact)})</strong><p>${safe(d.reason)}</p>${d.source_url?`<a href="${safe(d.source_url)}" target="_blank" rel="noopener noreferrer">Quelle ↗</a>`:''}${d.published_at?' · '+safe(d.published_at):''}</div>`).join('')||'<p>Keine belegt</p>'}<h3>Risiken</h3><ul>${r.risks.map(v=>`<li>${safe(v)}</li>`).join('')}</ul><h3>Neubewertung bei</h3><ul>${r.invalidation.map(v=>`<li>${safe(v)}</li>`).join('')}</ul></article>`:'<p class="cm-hint">Für dieses Paar ist noch keine ChatGPT-Analyse gespeichert.</p>'}</section>`;
$('#cm-pair').addEventListener('change',e=>{selected=e.target.value;notice='';render()});$('#cm-copy').addEventListener('click',async()=>{try{const data=await promptPayload();await navigator.clipboard.writeText(data);notice='Auftrag kopiert. Jetzt in ChatGPT einfügen.'}catch(e){notice='Kopieren blockiert. Bitte Browser-Berechtigungen prüfen: '+e.message}render()});$('#cm-open').addEventListener('click',()=>window.open('https://chatgpt.com/','_blank','noopener,noreferrer'));$('#cm-import').addEventListener('click',()=>{try{const x=parseReport($('#cm-response').value);if(x.pair!==selected)throw new Error('Das JSON gehört zu '+x.pair+', ausgewählt ist '+selected);storeReport(x);notice='Analyse gespeichert. '+x.pair+' · '+x.decision;render()}catch(e){$('#cm-status').textContent=e.message}});$('#cm-backup').addEventListener('click',()=>{const blob=new Blob([JSON.stringify({schema_version:'td-macro-reports-export-v1',reports:results()},null,2)],{type:'application/json'});const u=URL.createObjectURL(blob),a=document.createElement('a');a.href=u;a.download='tradingdesk-chatgpt-analysen.json';a.click();setTimeout(()=>URL.revokeObjectURL(u),5000)});
}
function start(){const nav=$('.main-nav');if(!nav)return;if($('#chatgpt-macro-nav'))return;const b=document.createElement('button');b.type='button';b.id='chatgpt-macro-nav';b.className='nav-item';b.innerHTML='<span class="nav-icon">✦</span> ChatGPT Makroanalyse';nav.append(b);b.addEventListener('click',e=>{e.preventDefault();e.stopImmediatePropagation();document.querySelectorAll('.nav-item').forEach(x=>x.classList.remove('active'));b.classList.add('active');const crumbs=$('#breadcrumbs');if(crumbs)crumbs.textContent='Workspace / ChatGPT Makroanalyse';notice='';render();},{capture:true})}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start);else start();
})();
