const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),path=require('node:path');
const root=path.resolve(__dirname,'..'),read=f=>fs.readFileSync(path.join(root,f),'utf8');
const version=JSON.parse(read('build-info.json')).version;
const ctx=vm.createContext({window:{},Intl});vm.runInContext(read('analytics.v'+version+'.js'),ctx);const A=ctx.window.FXAnalytics;
const trade=(id,r,status='Geschlossen')=>({id,kind:'trade',pair:'EURUSD',direction:'Long',status,closedAt:'2026-09-'+String(10+Number(id)).padStart(2,'0')+'T12:00',realizedR:r,fields:{},factors:{edgefinder:'Bestätigt',rates:'Bestätigt'}});
const rows=[trade(1,'2'),trade(2,'-1'),trade(3,'0'),trade(4,''),trade(5,' '),trade(6,'invalid'),trade(7,'100','Verworfen'),trade(8,'50','Offen')];
const original=JSON.stringify(rows);const selected=A.select(rows,{}),s=A.stats(selected.closed);
assert.equal(s.n,3);assert.equal(s.missing,3);assert.equal(s.sum,1);assert.equal(s.avg,1/3);assert(Math.abs(s.winRate-100/3)<1e-10);assert.equal(s.pf,2);assert.equal(s.flat,1);assert.equal(selected.open,1);assert.equal(selected.rejected.length,1);
assert.equal(A.stats([]).avg,null);assert.equal(A.stats([trade(1,0)]).pf,null);assert.equal(A.stats([trade(1,2)]).pf,null);assert.equal(A.stats([trade(1,-2)]).pf,0);
assert.equal(A.series([trade(1,2),trade(2,-1),trade(3,-2),trade(4,4)]).drawdown,3);
assert.equal(A.series([trade(1,-2)]).drawdown,2);
assert.equal(A.series([{...trade(1,10),closedAt:''}]).points.length,0);
assert.equal(A.day('2026-09-29T23:30:00Z'),'2026-09-30');assert.equal(A.day('2026-02-30'),'');
assert.equal(A.select(rows,{from:'2026-09-12',to:'2026-09-12'}).closed.length,1);
assert.equal(A.select(rows,{from:'2026-09-13',to:'2026-09-12'}).invalidRange,true);
assert.equal(A.select(rows,{pair:'USDCHF'}).closed.length,0);
assert.equal(A.select(rows,{direction:'Short'}).closed.length,0);
assert.equal(A.select([{...trade(1,1),closedAt:''}],{from:'2026-01-01'}).closed.length,0);
assert.equal(A.select([{...trade(1,1),closedAt:''}],{}).closed.length,1);
assert.equal(A.group(rows[0]),'Ohne passenden Bewertungsstand');
const t={...trade(9,''),status:'Idee',closedAt:''};A.capture(t,'Idee','Offen','2026-09-10T10:00:00Z');assert.equal(A.group(t),'EdgeFinder + Rates bestätigen');
const frozen=JSON.stringify(t.analyticsEntry);t.factors.rates='Widerspricht';A.capture(t,'Offen','Geschlossen','2026-09-11T10:00:00Z');assert.equal(JSON.stringify(t.analyticsEntry),frozen);assert.equal(A.group(t),'EdgeFinder + Rates bestätigen');
t.direction='Short';assert.equal(A.entry(t),null);t.direction='Long';t.pair='USDCHF';assert.equal(A.entry(t),null);
const old=trade(1,2);A.capture(old,'Geschlossen','Offen','2026-09-10T10:00:00Z');assert(!old.analyticsEntry);A.capture(old,'Watchlist','Offen','2026-09-10T10:00:00Z');assert(!old.analyticsEntry);
const legacy={...trade(1,''),closedAt:''};A.capture(legacy,'Offen','Geschlossen','2026-09-10T10:00:00Z');assert(!legacy.analyticsEntry);
const noFactors={...trade(1,''),closedAt:'',factors:{}};A.capture(noFactors,'Idee','Offen','2026-09-10T10:00:00Z');assert.equal(A.group(noFactors),'Bewertung unvollständig');
const html=A.render([...rows,{...trade(10,''),status:'Verworfen',notes:'<img src=x onerror=alert(1)>',fields:{rejectionReason:'<script>bad</script>'}}],{});assert(!html.includes('<img src=x'));assert(html.includes('&lt;script&gt;'));assert(html.includes('3 ohne Ergebnis'));assert.equal(JSON.stringify(rows),original,'Analytics never changes saved records');
// Exercise the actual core lifecycle, not just the standalone functions.
const nodes=new Map(),element=key=>{if(!nodes.has(key))nodes.set(key,{innerHTML:'',textContent:'',addEventListener(){},classList:{toggle(){},remove(){}},getBoundingClientRect(){return {height:70}},focus(){},querySelector(){return null}});return nodes.get(key)};
const listeners={};const dbData=new Map();const db={transaction(){const tx={objectStore(){return {put(v){dbData.set(v.id||v.key,JSON.parse(JSON.stringify(v)))}}}};queueMicrotask(()=>tx.oncomplete?.());return tx}};
const c=vm.createContext({window:{scrollTo(){},addEventListener(){}},document:{querySelector:element,querySelectorAll:()=>[],addEventListener:(k,v)=>listeners[k]=v,documentElement:{style:{setProperty(){}}}},localStorage:{getItem:()=>null},Intl,console,setTimeout:()=>0,clearTimeout(){},URL});
vm.runInContext(read('data.base.v'+version+'.js'),c);vm.runInContext(read('analytics.v'+version+'.js'),c);
vm.runInContext(read('app.base.v'+version+'.js').replace(/init\(\);\n\}\)\(\);\n$/,'window.test={state,defaultRecord,handleBound,duplicateRecord,render,saveNow,installEvents,analyticsFilters};\n})();\n'),c);
const T=c.window.test,record=T.defaultRecord('trade');record.pair='EURUSD';record.factors={edgefinder:'Bestätigt',rates:'Widerspricht'};
Object.assign(T.state,{records:[record],id:record.id,route:'trade',db});T.handleBound({dataset:{bind:'status'},value:'Offen'});assert(record.analyticsEntry);const at=record.analyticsEntry.capturedAt;
record.factors.rates='Bestätigt';T.handleBound({dataset:{bind:'status'},value:'Geschlossen'});record.realizedR='-1';assert.equal(record.analyticsEntry.capturedAt,at);assert.equal(record.analyticsEntry.factors.rates,'Widerspricht');
T.state.route='analytics';T.state.id=null;T.render();assert(element('#view').innerHTML.includes('EdgeFinder bestätigt, Rates widersprechen'));
T.installEvents();listeners.change({target:{dataset:{analyticsFilter:'pair'},value:'USDCHF'}});assert.equal(T.analyticsFilters.pair,'USDCHF');
T.state.route='trade';T.state.id=record.id;T.duplicateRecord();const copy=T.state.records.find(r=>r.id!==record.id);assert(!copy.analyticsEntry);assert(!copy.analyticsRejectedAt);assert.equal(record.analyticsEntry.capturedAt,at);
(async()=>{await T.saveNow();assert.equal(dbData.get(record.id).analyticsEntry.capturedAt,at);assert(!dbData.get(copy.id).analyticsEntry);console.log('PASS: analytics metrics, missing/zero values, dates, exclusions, snapshots, legacy/reopen/duplicate behavior, filters, persistence and escaping.');})().catch(e=>{console.error(e);process.exitCode=1});
