const fs=require('fs');
const assert=require('assert');
const index=fs.readFileSync('index.html','utf8');
const addon=fs.readFileSync('app.v5.6.11.js','utf8');
assert(index.includes('v5.6.11'));
assert(index.includes('data.base.v5.6.11.js'));
assert(index.includes('app.base.v5.6.11.js'));
assert(index.includes('app.v5.6.11.js'));
assert(index.includes('style.v5.6.11.css'));
for(const marker of ['Rates-Bestätigungsmatrix','Zentralbanken & Sitzungswahrscheinlichkeiten','probHike','probHold','probCut','macroSnapshot'])assert(addon.includes(marker),marker+' fehlt');
console.log('v5.6.11 trade fundamentals layer: OK');
